### ISSUE TITLE
Hunt Flaky tests 

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2129]
This one is tricky, but will be so much appreciated by devs/contributors (in particular by first-time-contributors)

We have some usual suspects that normally break once in a while (1 out of 3 travis builds):

- spec/features/tracks_spec.rb (I can't find any examples right now on travis)

- spec/shared/features/nested_imageable.rb
https://travis-ci.org/consul/consul/jobs/301885841

- spec/features/admin/stats_spec.rb
https://travis-ci.org/consul/consul/jobs/285994433
https://travis-ci.org/consul/consul/jobs/278592658
https://travis-ci.org/consul/consul/jobs/285995193

There are many others that fail because of `Unknown error while speaking to annotation store! [object Object]` like https://travis-ci.org/consul/consul/jobs/291110815 or `TypeError: undefined is not an object (evaluating 'this.document.getWindow().$.getSelection')` like https://travis-ci.org/consul/consul/jobs/301885842

We'll try to be conscious about this issue, and instead of rebuilding failed travis builds, copy&paste here tests that seem to be flaky (the rspec failure output) to make it easier to narrow whats going on at each one.

**Comment by bertocq** [comment]
Another set of suspected flaky specs:

## Failures
```ruby
Failures:
  1) Votes Debates Single debate Update
     Failure/Error: expect(page).to have_css("a.no-voted")
       expected to find css "a.no-voted" but there were no matches
     # ./spec/features/votes_spec.rb:90:in `block (5 levels) in <top (required)>'
     # ./spec/features/votes_spec.rb:88:in `block (4 levels) in <top (required)>'
  2) Commenting legislation questions Sanitizes comment body for security
     Failure/Error: expect(page).to have_content "click me http://www.url.com"
       expected to find text "click me http://www.url.com" in "Manuela2653 • Author • 2017-11-15 19:42:03 a comment No votes | I agree 0 I disagree 0 No responses"
     # ./spec/features/comments/legislation_annotations_spec.rb:163:in `block (3 levels) in <top (required)>'
     # ./spec/features/comments/legislation_annotations_spec.rb:162:in `block (2 levels) in <top (required)>'
  3) Commenting legislation questions Index
     Failure/Error: expect(page).to have_content comment.user.name
       expected to find text "Manuela2655" in "Manuela2658 • 2017-11-15 19:42:04 Comment body 207 No votes | I agree 0 I disagree 0 No responses"
     # ./spec/features/comments/legislation_annotations_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/features/comments/legislation_annotations_spec.rb:18:in `block (2 levels) in <top (required)>'
```

## Failed examples:
```ruby
rspec ./spec/features/votes_spec.rb:82 # Votes Debates Single debate Update
rspec ./spec/features/comments/legislation_annotations_spec.rb:154 # Commenting legislation questions Sanitizes comment body for security
rspec ./spec/features/comments/legislation_annotations_spec.rb:8 # Commenting legislation questions Index
```
## Randomized with seed 31952

**Comment by aitbw** [comment]
A short update on this: We have achieved some initial success fixing flaky specs all around CONSUL, which you can find [here](https://github.com/wairbut-m2c/consul/commits/aperez-fix-flaky-tests) —the changes are minimal but they've been tested several times on a local environment without failures as well as on TravisCI (commits have been built at least 3 times each successfully)

We've also managed to reproduce some of the flaky specs (related to [Nested Imageable](https://github.com/wairbut-m2c/consul/blob/aperez-fix-flaky-tests/spec/shared/features/nested_imageable.rb)) on a local environment and we are currently investigating.

**Comment by iagirre** [comment]
I've got this error today, and I'm pretty sure I also got it some time ago:

![flaky01](https://user-images.githubusercontent.com/31625251/32935832-1f260584-cb72-11e7-9601-70fae4edb9f1.png)

I hope it helps

**Comment by iagirre** [comment]
```
Failures:
  1) Proposals behaves like nested imageable at new_proposal_path Should show successful notice when resource filled correctly and after valid file uploads
     Failure/Error: expect(page).to have_content imageable_success_notice
       expected to find text "Proposal created successfully" in "CONSUL Language: Transparency Open data CONSUL Admin Notifications My activity My account Sign out Debates Proposals Voting Legislation processes [...]"
     Shared Example Group: "nested imageable" called from ./spec/features/proposals_spec.rb:1384
     # ./spec/shared/features/nested_imageable.rb:160:in `block (3 levels) in <top (required)>'
  2) Proposals behaves like nested imageable at new_proposal_path Should show new image after successful creation with one uploaded file
     Failure/Error: image = find(".image")
     
     Capybara::ElementNotFound:
       Unable to find css ".image"
     Shared Example Group: "nested imageable" called from ./spec/features/proposals_spec.rb:1384
     # ./spec/shared/features/nested_imageable.rb:232:in `block in imageable_attach_new_file'
     # ./spec/shared/features/nested_imageable.rb:231:in `imageable_attach_new_file'
     # ./spec/shared/features/nested_imageable.rb:168:in `block (3 levels) in <top (required)>'
```

**Comment by iagirre** [comment]
I got this right now, about nested_imageable and proposals.

### Failures:
```
Failures:
  1) Proposals behaves like nested imageable at new_proposal_path Should show successful notice when resource filled correctly and after valid file uploads
     Failure/Error: expect(page).to have_content imageable_success_notice
       expected to find text "Proposal created successfully" in "CONSUL Language: Transparency Open data CONSUL Admin Notifications My activity My account Sign out Debates Proposals Voting Legislation processes Participatory budgeting More information Go back Create new proposal How do citizen proposals work? × 1 error prevented this Proposal from being saved: Proposal title Proposal question Must be summarised in one question with a Yes or No answer. E.g. 'Do you agree with the pedestrianisation of Calle Mayor?' Proposal summary (maximum 200 characters) Proposal text ◢ Link to external video You may add a link to YouTube or Vimeo Link to additional documentation Descriptive image You can upload one image of following content types: jpeg, jpg, up to 1 MB. Title Remove image Documents You can upload up to a maximum of 3 documents of following content types: pdf, up to 3 MB per file. Add new document Scope of operation Tags Tag this proposal. You can choose from proposed categories or add your own Categories must be accepted I agree to the Privacy Policy and the Terms and conditions of use Recommendations for creating a proposal Do not use capital letters for the proposal title or for whole sentences. On the internet, this is considered shouting. And nobody likes being shouted at. Any proposal or comment suggesting illegal action will be deleted, as well as those intending to sabotage the debate spaces. Anything else is allowed. Enjoy this space and the voices that fill it. It belongs to you too. Open government This portal uses the CONSUL application which is open-source software. For technical assistance enters technical assistance Participation Decide how to shape the city you want to live in. Transparency Find out anything about the city. Open data Every detail about the City Council is yours to access. CONSUL, 2017 | Privacy Policy | Terms and conditions of use | Accessibility"
     Shared Example Group: "nested imageable" called from ./spec/features/proposals_spec.rb:1384
     # ./spec/shared/features/nested_imageable.rb:160:in `block (3 levels) in <top (required)>'
  2) Proposals behaves like nested imageable at new_proposal_path Should show new image after successful creation with one uploaded file
     Failure/Error: image = find(".image")
     
     Capybara::ElementNotFound:
       Unable to find css ".image"
     Shared Example Group: "nested imageable" called from ./spec/features/proposals_spec.rb:1384
     # ./spec/shared/features/nested_imageable.rb:232:in `block in imageable_attach_new_file'
     # ./spec/shared/features/nested_imageable.rb:231:in `imageable_attach_new_file'
     # ./spec/shared/features/nested_imageable.rb:168:in `block (3 levels) in <top (required)>'
```
### Failed examples:
```
Failed examples:
rspec ./spec/features/proposals_spec.rb[1:31:1:13] # Proposals behaves like nested imageable at new_proposal_path Should show successful notice when resource filled correctly and after valid file uploads
rspec ./spec/features/proposals_spec.rb[1:31:1:14] # Proposals behaves like nested imageable at new_proposal_path Should show new image after successful creation with one uploaded file
```

### Randomized with seed 44925

**Comment by iagirre** [comment]
Another one:

### Failures:
```
Failures:
1) Legislation Draft Versions See draft text page switches to another version with js
     Failure/Error: expect(page).to_not have_content("Body of the first version")
     
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       Unknown error while speaking to annotation store! [object Object]
       Unknown error while speaking to annotation store! [object Object]
           at http://127.0.0.1:46377/assets/application-48bd980b2cd3f10fce82acbd11213d1e9284dd2c5ff7ed59c3e763c05d530dc6.js:45163
     # ./spec/features/legislation/draft_versions_spec.rb:64:in `block (3 levels) in <top (required)>'
```
### Failed examples:
```
Failed examples:
rspec ./spec/features/legislation/draft_versions_spec.rb:58 # Legislation Draft Versions See draft text page switches to another version with js
```

### Randomized with seed 60918

**Comment by aitbw** [comment]
Here's another one.

![screenshot_2017-11-20_14-56-43](https://user-images.githubusercontent.com/9470839/33035888-15bd6058-ce03-11e7-8578-e8fe64ccabdb.png)

A quick update on this: Most flaky specs are related to `Nested Imageable` or race conditions. I think we should opt for a refactor (mostly related when creating objects) in order to solve this issue.

**Comment by bertocq** [comment]
One more 🙈 
```
  1) Budget Investments behaves like nested documentable at new_budget_investment_path Should show max documents warning when max documents allowed limit is reached
     Failure/Error: expect(page).to have_css ".max-documents-notice", visible: true
       expected to find css ".max-documents-notice" but there were no matches. Also found "", which matched the selector but not all filters.
     Shared Example Group: "nested documentable" called from ./spec/features/budgets/investments_spec.rb:479
     # ./spec/shared/features/nested_documentable.rb:55:in `block (3 levels) in <top (required)>'
````

**Comment by bertocq** [comment]
Yes @aitbw seems like both nested documentable and nested imageable are the root of 80% of flaky tests right now, do you want to draft a proposal of that refactor?

**Comment by iagirre** [comment]
I think I got another one:

### Failures:
```
Failures:
  1) Proposals behaves like mappable At edit_proposal_path Can not display map on proposal edit when remove map marker
     Failure/Error: click_on "Save changes"
     
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       Error: [CKEDITOR.resourceManager.load] Resource name "default" was not found at "http://127.0.0.1:37659/assets/ckeditor/styles.js?t=H5SC".
       Error: [CKEDITOR.resourceManager.load] Resource name "default" was not found at "http://127.0.0.1:37659/assets/ckeditor/styles.js?t=H5SC".
           at http://127.0.0.1:37659/assets/application-48bd980b2cd3f10fce82acbd11213d1e9284dd2c5ff7ed59c3e763c05d530dc6.js:30667
           at http://127.0.0.1:37659/assets/application-48bd980b2cd3f10fce82acbd11213d1e9284dd2c5ff7ed59c3e763c05d530dc6.js:30662 in f
           at http://127.0.0.1:37659/assets/application-48bd980b2cd3f10fce82acbd11213d1e9284dd2c5ff7ed59c3e763c05d530dc6.js:30662 in C
           at http://127.0.0.1:37659/assets/application-48bd980b2cd3f10fce82acbd11213d1e9284dd2c5ff7ed59c3e763c05d530dc6.js:30662 in w
           at http://127.0.0.1:37659/assets/application-48bd980b2cd3f10fce82acbd11213d1e9284dd2c5ff7ed59c3e763c05d530dc6.js:30663 in onerror
     Shared Example Group: "mappable" called from ./spec/features/proposals_spec.rb:1420
     # ./spec/shared/features/mappable.rb:125:in `block (3 levels) in <top (required)>'
```
### Failed examples:
```
Failed examples:
rspec ./spec/features/proposals_spec.rb[1:36:2:4] # Proposals behaves like mappable At edit_proposal_path Can not display map on proposal edit when remove map marker
```

### Randomized with seed 38698

**Comment by voodoorai2000** [comment]
Hey @aitbw have you already started on that draft for imageable specs?

**Comment by bertocq** [comment]
This issue isn't really useful as we forget to update with new flakies, and no-one can really tackle more than one at a time. Closing in favour of using new Flaky Spec issue template to have individual and more actionable issues https://github.com/consul/consul/issues/new?template=flakies.md

🙏  whenever you see a travis build failing and you're sure its a flaky (is not possible to reproduce the error in localhost running the spec or entire tests file) create a new issue filling just 3 fields! (title, seed and failure text)
