### ISSUE TITLE
Improve Admin Settings section

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2586]
The Admin panel settings view is really long.

It would be an improvement to split it into multiple submenus:
- Configuration settings
- Features
- Banner styles
- Banner images
- Map configuration

**Comment by aamarill** [comment]
@bertocq I would like to work on this 😄 Can I be assigned? Thank you!

**Comment by decabeza** [comment]
Hi @aamarill, you can use the mockups of https://github.com/consul/consul/issues/1597 as a reference 😉 

Don't worry about styles 😌, we only need the split in tabs (there is a lot of tabs menus on admin panel as an example)

**Comment by aamarill** [comment]
Thank you @decabeza I am on it! 💪

**Comment by aamarill** [comment]
@decabeza @bertocq I am stuck initializing the database. I have been troubleshooting all day and I still can't get it to work. Any ideas? ( I am using PostgreSQL 10.4)

This is what I get during `$ bin/rake db:create`
```shell
~/Bloc/Module_6/consul $ bin/rake db:create
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.6-compliant syntax, but you are running 2.3.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/adanamarillas/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/adanamarillas/.rvm/gems/ruby-2.3.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "consul_development" does not exist
 (ActiveRecord::NoDatabaseError)
```
This is followed by a bunch of other failures, but I left it out since I assume it's not as important. Thank you!!

**Comment by decabeza** [comment]
Hi @aamarill,

Sometimes I have to remove and reset the database and I use:

```shell
rake db:drop
rake db:create
rake db:migrate 
rake db:migrate RAILS_ENV=test
rake db:dev_seed
```

If you wanna try, this steps works nice for me 😉

**Comment by aamarill** [comment]
@decabeza Thanks for the suggestion. Even though my site was already working, I ran the steps you suggested and it works perfectly.  Thanks! 🙌

**Comment by aamarill** [comment]
Hey @decabeza or @bertocq, 

I am a little confused as to where the submenus (or tabs) need to go. To they go on the top, or should they be on the left-side menu that is already there?

From the picture below, should they be on the green or red area? Thanks and sorry for any confusion! 😄 

<img width="1440" alt="consul setting re-work" src="https://user-images.githubusercontent.com/29871004/40395693-28fcccba-5dde-11e8-9514-d5d4a988583d.png">

**Comment by decabeza** [comment]
Hi @aamarill, don't worry 😉 

You can add one "Settings" link on the sidebar (green area), this link is the same as the gear icon in the header.  And the tabs should go on the top (red area). 😌 

Thanks!

**Comment by aamarill** [comment]
Thanks @decabeza! I am on it 💪

**Comment by aamarill** [comment]
@decabeza what convention do we want here?

This convention follows all of the other side-menu items:
`<strong><%= t("admin.menu.settings") %></strong>`

Displays ("Settings Configuration")
<img width="1003" alt="screen shot 2018-05-23 at 1 59 35 pm" src="https://user-images.githubusercontent.com/29871004/40450931-ef38531e-5e91-11e8-881d-ca828e7aa2c6.png">

Or, 
Do we want this?
`<strong>Settings</strong>`

Which displays just "Settings" (single word):
<img width="985" alt="screen shot 2018-05-23 at 1 55 29 pm" src="https://user-images.githubusercontent.com/29871004/40451030-23c812e0-5e92-11e8-8cf9-0b2b963a675c.png">


It seems "configuration" is part of "settings"? Let me know if my question makes any sense 😅 
Thanks!

**Comment by decabeza** [comment]
Hi @aamarill,

The correct is use the i18n keys. So... use `<%= t("admin.menu.settings") %>` and you can change "Configuration settings" to "Settings" to avoid confusions 😉 

Also, could you please change the hardcoded texts to i18n keys (I indicated on your PR). Thank you again! 🙏 😌

**Comment by TomClive** [comment]
> Hi @aamarill,
> 
> Sometimes I have to remove and reset the database and I use:
> 
> ```shell
> rake db:drop
> rake db:create
> rake db:migrate 
> rake db:migrate RAILS_ENV=test
> rake db:dev_seed
> ```
> 
> If you wanna try, this steps works nice for me 😉

These steps got my local installation working too. I was getting the same database does not exist error as @aamarill I've seen a few others raise this on Slack etc but this is the solution worked for me before I tried manually adding the database.
