### ISSUE TITLE
Docker issue with 

### ISSUE THREAD

**Issue by petrk94** [consul/consul#3031]
### User Story

I want to use docker to get consul installed on my VPS server. But it doesnt work properly.

### Description

When I start the `bundle install` command in the consul directory, I get this error message
```
root@vmd31906:~/consul# docker-compose run app rake db:migrate
Starting consul_database_1 ... done
+ stat -c %u /var/www/consul/Gemfile
+ USER_UID=0
+ stat -c %g /var/www/consul/Gemfile
+ USER_GID=0
+ export USER_UID
+ export USER_GID
+ usermod -u 0 consul
+ groupmod -g 0 consul
+ usermod -g 0 consul
+ chown -R -h 0 /usr/local/bundle
+ chgrp -R -h 0 /usr/local/bundle
+ /usr/bin/sudo -EH -u consul rake db:migrate
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.7-compliant syntax, but you are running 2.3.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Rails Error: Unable to access log file. Please ensure that /var/www/consul/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /var/www/consul/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /var/www/consul/log/delayed_job.log
/var/www/consul/config/initializers/delayed_job_config.rb:13:in `new'
/var/www/consul/config/initializers/delayed_job_config.rb:13:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/var/www/consul/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/www/consul/log/delayed_job.log
/var/www/consul/config/initializers/delayed_job_config.rb:13:in `new'
/var/www/consul/config/initializers/delayed_job_config.rb:13:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/var/www/consul/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

```

I hope you can help here.
I followed the manual installation process for docker
https://consul_docs.gitbooks.io/docs/en/getting_started/docker.html

Thanks

**Comment by asolera** [comment]
I found out that this pull request (#2661) is causing those permission errors.

I just reverted back `Dockerfile` and `docker-compose.yml` to its previous version and everything worked fine.
