### ISSUE TITLE
Flaky spec: Each user has a different and consistent random proposals order

### ISSUE THREAD

**Issue by microweb10** [consul/consul#3075]
## References

* Original issue AyuntamientoMadrid#1659
* The spec in issue #3368 seems to fail for the same reason
* Pull requests #3076, #3085 and #3321 fixed some of the reasons why this spec fails sometimes
* Failures in [Travis build 27850, job 1](https://travis-ci.org/consul/consul/jobs/502500600) and [Travis build 27875, job 2](https://travis-ci.org/consul/consul/jobs/503256161)

## Failure
```bash
1) Legislation Proposals Random pagination Random order maintained with pagination
     Failure/Error: expect(legislation_proposals_order).to eq(first_page_proposals_order)
       expected: ["legislation_proposal_14", "legislation_proposal_14_votes", "legislation_proposal_8", "legislation_p...osal_5", "legislation_proposal_5_votes", "legislation_proposal_11", "legislation_proposal_11_votes"]
            got: ["legislation_proposal_1", "legislation_proposal_1_votes", "legislation_proposal_7", "legislation_pro...osal_10", "legislation_proposal_10_votes", "legislation_proposal_4", "legislation_proposal_4_votes"]
       (compared using ==)
     # ./spec/features/legislation/proposals_spec.rb:73:in `block (3 levels) in <top (required)>'
```

Another possible failure is:

```bash
Failures:
  1) Legislation Proposals Random pagination Each user has a different and consistent random proposals order
     Failure/Error: expect(legislation_proposals_order).to eq(@second_user_proposals_order)
       expected: ["legislation_proposal_24", "legislation_proposal_24_votes", "legislation_proposal_16", "legislation_...al_27", "legislation_proposal_27_votes", "legislation_proposal_22", "legislation_proposal_22_votes"]
            got: ["legislation_proposal_20", "legislation_proposal_20_votes", "legislation_proposal_27", "legislation_...al_17", "legislation_proposal_17_votes", "legislation_proposal_22", "legislation_proposal_22_votes"]
     
       (compared using ==)
     # ./spec/features/legislation/proposals_spec.rb:42:in `block (3 levels) in <top (required)>'
     # ./spec/sessions_helper.rb:5:in `in_browser'
     # ./spec/features/legislation/proposals_spec.rb:40:in `block (2 levels) in <top (required)>'
```

## Cause

Right now the reason why the same user gets different results is unknown. There have been issues related to Capybara sessions and to PostgreSQL's `setseed()` command. The Capybara sessions usage was simplified in #3076 and we stopped using `setseed()` after merging #3321.

**Comment by javierm** [comment]
It's failed again: https://travis-ci.org/consul/consul/jobs/502500600
