### ISSUE TITLE
NameError: uninitialized constant Faker

### ISSUE THREAD

**Issue by KrzysztofMadejski** [consul/consul#3110]
### User Story

As a tech admin I want to setup demo with dev_seeds.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

Running `rake db:dev_seed` resulted in error below.

```
Creating Settings ✅
Creating Geozones ✅
Creating Usersrake aborted!
NameError: uninitialized constant Faker
/var/www/consul/db/dev_seeds/users.rb:26:in `block in <top (required)>'
/var/www/consul/db/dev_seeds.rb:10:in `section'
/var/www/consul/db/dev_seeds/users.rb:1:in `<top (required)>'
/var/www/consul/db/dev_seeds.rb:20:in `require_relative'
/var/www/consul/db/dev_seeds.rb:20:in `<top (required)>'
/var/www/consul/lib/tasks/db.rake:5:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:dev_seed
```

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

All seeds are created.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by KrzysztofMadejski** [comment]
It happened because I was running in `production` environment. Faker is available only in development.
