### ISSUE TITLE
ActionController::InvalidAuthenticityToken on Local installation Login

### ISSUE THREAD

**Issue by mbreslein-thd** [consul/consul#4688]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:Bug

I set up a Local Installation on an Ubuntu-Machine. Because we want to test it with multiple people (and accessing port 3000 from a different PC in the network didn't work)  I set up an reverse-proxy with nginx to access consul on port 80.
Clicking trough it works fine but the login with the given credentials is broken.

### Current Behavior
[comment]: # (Describe what actually happened.)
When entering the creds listed at the end of the setup guide It gives me this error-message:

```
ActionController::InvalidAuthenticityToken in Users::SessionsController#create
```

Extracted source (around line 215):
```
 def handle_unverified_request
          raise ActionController::InvalidAuthenticityToken
        end
      end
    end
```

Full Trace:
```
actionpack (5.2.6) lib/action_controller/metal/request_forgery_protection.rb:215:in `handle_unverified_request'
actionpack (5.2.6) lib/action_controller/metal/request_forgery_protection.rb:247:in `handle_unverified_request'
devise (4.8.0) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
actionpack (5.2.6) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
activesupport (5.2.6) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.6) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.6) lib/active_support/callbacks.rb:199:in `block in halting'
activesupport (5.2.6) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.6) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.6) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.6) lib/active_support/callbacks.rb:107:in `block in run_callbacks'
activesupport (5.2.6) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.6) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.6) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.6) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.6) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.6) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
turnout (2.5.0) lib/rack/turnout.rb:25:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
bullet (6.1.4) lib/bullet/rack.rb:15:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/cookies.rb:670:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activerecord (5.2.6) lib/active_record/migration.rb:559:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
airbrake (7.4.0) lib/airbrake/rack/middleware.rb:48:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rollbar (3.2.0) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
rollbar (3.2.0) lib/rollbar.rb:145:in `scoped'
rollbar (3.2.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
rollbar (3.2.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `call'
ahoy_matey (3.2.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
puma (4.3.8) lib/puma/configuration.rb:228:in `call'
puma (4.3.8) lib/puma/server.rb:718:in `handle_request'
puma (4.3.8) lib/puma/server.rb:472:in `process_client'
puma (4.3.8) lib/puma/server.rb:328:in `block in run'
puma (4.3.8) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

Request Parameters
```
{"utf8"=>"✓",
 "authenticity_token"=>"LGqLxnslpTzxhS4iClo2vCcYcOEjcNWC+73mCOI1N/tz/IcDvd2Jb1mSfSGjcsYauQmxAFtgwYkE1nByXAi/cQ==",
 "user"=>{"login"=>"admin@consul.dev", "password"=>"[FILTERED]", "remember_me"=>"0"},
 "commit"=>"Enter"}
```

session dump
```
_csrf_token: "DoQTKdFtc5FLsNZWmEJOTV+ASyuzBpWpsjLTa4AjX3Y="
invisible_captcha_timestamp: "2021-09-02T15:43:27+02:00"
locale: "en"
session_id: "191a2ae69fc559b01e59c758d62e41e9"
user_return_to: "/"
```

env dump
```
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.9,de;q=0.8"
HTTP_CACHE_CONTROL: "max-age=0"
HTTP_ORIGIN: "http://192.168.220.49"
HTTP_VERSION: "HTTP/1.0"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "127.0.0.1"
SERVER_NAME: "127.0.0.1"
SERVER_PROTOCOL: "HTTP/1.1"
```

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Being able to log in withe the credentials from the guide.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

1. Create a Local installation according to guide
2. Set up a nginx reverse-proxy to access the page on :80
3. Try to log in at http://<IP>/users/sign_in

**Comment by javierm** [comment]
Hi, @mbreslein-thd :smile:.

This looks like a problem related to integrating a Rails application with the nginx reverse proxy. We don't have much experience with setting up reverse proxies in development, so here are some results found after a quick search:

* [InvalidAuthenticityToken in Rails 5 behind Nginx using SSL](https://stackoverflow.com/questions/34655545/invalidauthenticitytoken-in-rails-5-behind-nginx-using-ssl)
* [ActionController::InvalidAuthenticityToken at login using NGINX and Rails](https://stackoverflow.com/questions/58872323/actioncontrollerinvalidauthenticitytoken-at-login-using-nginx-and-rails)
* [Can't verify CSRF token authenticity in Rails 6 with SSL nginx reverse proxy](https://stackoverflow.com/questions/63942677/cant-verify-csrf-token-authenticity-in-rails-6-with-ssl-nginx-reverse-proxy)

Hope that helps!

**Comment by mbreslein-thd** [comment]
Thanks for the pointers.
(I totally forgot that I could just google it)

In case someone in the future has the same problem as me, here's a nginx-config that works:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name <Your_SERVER_NAME>;

    location / {
        proxy_pass http://localhost:3000;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Origin https://$http_host;
        proxy_redirect off;
    }

    ssl on;
    ssl_certificate <SSL-CERT>;
    ssl_certificate_key <SSL-KEY>;
}
```
Just replace <Your_SERVER_NAME>, <SSL-CERT> and <SSL-KEY> and it works.
