### ISSUE TITLE
Heroku deploy LoadError: cannot load such file -- net/smtp

### ISSUE THREAD

**Issue by thebravoman** [consul/consul#5027]
### User Story

Trying to deploy on heroku

### Why is this Needed?

To host it
### Description

git push heroku master

### Current Behavior
```
remote: -----> Installing node-v16.13.1-linux-x64
remote: -----> Detecting rake tasks
remote: 
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: cannot load such file -- net/smtp
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/recipient_interceptor-0.3.1/lib/recipient_interceptor.rb:1:in `<top (required)>'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
remote:  !     /tmp/build_91a9b9c2/config/application.rb:20:in `<top (required)>'
remote:  !     /tmp/build_91a9b9c2/Rakefile:4:in `require'
remote:  !     /tmp/build_91a9b9c2/Rakefile:4:in `<top (required)>'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
remote:  !     /tmp/build_91a9b9c2/bin/rake:4:in `<main>'
remote:  !
remote: /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:100:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: LoadError: cannot load such file -- net/smtp
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/recipient_interceptor-0.3.1/lib/recipient_interceptor.rb:1:in `<top (required)>'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
remote: /tmp/build_91a9b9c2/config/application.rb:20:in `<top (required)>'
remote: /tmp/build_91a9b9c2/Rakefile:4:in `require'
remote: /tmp/build_91a9b9c2/Rakefile:4:in `<top (required)>'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build_91a9b9c2/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
remote: /tmp/build_91a9b9c2/bin/rake:4:in `<main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:967:in `rake'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:69:in `block in run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:63:in `run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:103:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:988:in `allow_git'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:96:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:55:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:37:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:30:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:17:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:18:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to promeni-consul.
remote: 
To https://git.heroku.com/promeni-consul.git
 ! [remote rejected]     master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/promeni-consul.git'
```

### Expected Behavior
It deploys

### Steps to reproduce

git push heroku master

### Definition of Done
It deploys on heroku

I was able to solve this by adding 

```
gem 'net-smtp', require: false
```

Do you want me to prepare a PR? Would it be accepted

**Comment by javierm** [comment]
Sorry, I missed this one. Quoting #5028 

> The application doesn't work with Ruby 3 yet. You need to use Ruby 2.7.6, as specified in the `.ruby-version` file.
>
> Since I see you've also opened issue #5029 :+1:, closing in favor of that one.
