### ISSUE TITLE
Heroku deploy - remote:  !     ArgumentError: wrong number of arguments (given 3, expected 1..2)

### ISSUE THREAD

**Issue by thebravoman** [consul/consul#5028]
### User Story

Deploying on heroku

### Why is this Needed?

To use it

### Description

```
git push heroku master
```

### Current Behavior
```
remote: -----> Installing node-v16.13.1-linux-x64
remote: -----> Detecting rake tasks
remote: 
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     ArgumentError: wrong number of arguments (given 3, expected 1..2)
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/definition.rb:30:in `initialize'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/options.rb:17:in `new'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/options.rb:17:in `with'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/builder.rb:66:in `constructor'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:42:in `block in <module:Types>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:41:in `each'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:41:in `<module:Types>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:4:in `<module:Dry>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:3:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types.rb:152:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry-types.rb:1:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-struct-0.5.1/lib/dry/struct.rb:1:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-struct-0.5.1/lib/dry-struct.rb:1:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/translator-text-0.1.0/lib/translator_text/types.rb:1:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/translator-text-0.1.0/lib/translator-text.rb:4:in `require_relative'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/translator-text-0.1.0/lib/translator-text.rb:4:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
remote:  !     /tmp/build_199ddb66/config/application.rb:20:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/Rakefile:4:in `require'
remote:  !     /tmp/build_199ddb66/Rakefile:4:in `<top (required)>'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
remote:  !     /tmp/build_199ddb66/bin/rake:4:in `<main>'
remote:  !
remote: /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:100:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: ArgumentError: wrong number of arguments (given 3, expected 1..2)
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/definition.rb:30:in `initialize'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/options.rb:17:in `new'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/options.rb:17:in `with'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/builder.rb:66:in `constructor'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:42:in `block in <module:Types>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:41:in `each'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:41:in `<module:Types>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:4:in `<module:Dry>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types/core.rb:3:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry/types.rb:152:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-types-0.13.3/lib/dry-types.rb:1:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-struct-0.5.1/lib/dry/struct.rb:1:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/dry-struct-0.5.1/lib/dry-struct.rb:1:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `block in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:291:in `load_dependency'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.5.1/lib/active_support/dependencies.rb:324:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/translator-text-0.1.0/lib/translator_text/types.rb:1:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/translator-text-0.1.0/lib/translator-text.rb:4:in `require_relative'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/translator-text-0.1.0/lib/translator-text.rb:4:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
remote: /tmp/build_199ddb66/config/application.rb:20:in `<top (required)>'
remote: /tmp/build_199ddb66/Rakefile:4:in `require'
remote: /tmp/build_199ddb66/Rakefile:4:in `<top (required)>'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build_199ddb66/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
remote: /tmp/build_199ddb66/bin/rake:4:in `<main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:967:in `rake'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:69:in `block in run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:63:in `run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:103:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:988:in `allow_git'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:96:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:55:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:37:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:30:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:17:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:18:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to promeni-consul.
remote: 
To https://git.heroku.com/promeni-consul.git
 ! [remote rejected]     master -> master (pre-receive hook declined)

```

### Expected Behavior
It works

### Steps to reproduce
```
git push heroku master
```

### Definition of Done

Can use it on heroku

**Comment by thebravoman** [comment]
Down the rabbit hole we can not upgrade dry-types to 1.0.0 because of 

```
Resolving dependencies....
Bundler could not find compatible versions for gem "dry-types":
  In Gemfile:
    dry-types (~> 1.0)

    translator-text (~> 0.1.0) was resolved to 0.1.0, which depends on
      dry-struct (~> 0.5.0) was resolved to 0.5.1, which depends on
        dry-types (~> 0.13)
```

Guess we can't run it with ruby-3.1.2

Are we supposed to?

**Comment by javierm** [comment]
Hi, @thebravoman :smile:.

The application doesn't work with Ruby 3 yet. You need to use Ruby 2.7.6, as specified in the `.ruby-version` file.

Since I see you've also opened issue #5029 :+1:, closing in favor of that one.

**Comment by thebravoman** [comment]
Thanks. Makes sense.
